<a href="https://colab.research.google.com/github/AndreasPB/ai-stuff/blob/master/bad_chat_gpt_clone.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Building a bad Generatively Pretrained Transformer (GPT) by following https://youtu.be/kCc8FmEb1nYs

In [1]:
# Read some txt dataset
with open('steam_reviews.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [2]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  23930571


In [3]:
# Let's look at the first 1000 characters
print(text[:1000])

review_text

Ruined my life.

This will be more of a ''my experience with this game'' type of review, because saying things like ''great gameplay'' will not suit something I've experienced with Counter-Strike. Here you go:  I remember back in 2002 I was at a friend's house and he was playing a game. I didn't know the name of the game nor I had internet to find it. A few weeks passed by and another friend came over. He didn't have a computer, so he brought a disc with a game in it. He told me that it was one of the best games and from that very moment I knew that it is going to be the game I saw at the other friend's house. When I saw the Counter-Strike logo I was filled with gamegasm (?) and I was so happy. I was playing it hardcore. Made friends, clans, was involved in communities and even made two myself. Counter-Strike is my first game which I played competitively and it was a such an experience. Playing public servers with mods were very fun, but playing it competitively made it ve

In [4]:
# Here are all the unique characters that occur in this text
chars = sorted(set(text))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !#$%&'()*+,-./0123456789:;=?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~“”¡¢£¥§¨©ª«¬®¯°²³´¶·¸º»¼½¾¿ÀÁÂÃÄÅÆÉÌÍÎÓÖØÜßàáãäçèéêëìíñòóôõöøùúüĆćČčđĚğİıŁœşŠšŽžƁƅƊƒƓƖƛƝƠƤƦƧƬƲƳƵƽɐɑɔɗɦɪʖʰʳʷʸˇˈ̴̵̶̷̸̡̢̧̨̛̖̗̘̙̜̝̞̟̠̣̤̥̦̩̪̫̬̭̮̯̰̱̲̳̹̺̻̼͇͈͉͍͎̀́̂̃̄̅̆̇̈̉̊̋̌̍̎̏̐̑̒̓̔̽̾̿̀́͂̓̈́͆͊͋͌̕̚ͅ͏͓͔͕͖͙͚͐͑͒͗͛ͣͤͥͦͧͨͩͪͫͬͭͮͯ͘͜͟͢͝͞͠͡ΘεηιλπυφωЄАБВГДЕЗИКЛМНОПРСТУХЧШЬЭЯабвгдежзийклмнопрстуфхцчшщъыьэюяёєѕїѠ҂҉үӇԁل۞۩ਉଠஜ௵థ౦౪ಠಥกคงจฉชดตถทนบปผพภมยรลวสหอะัาำิีืุูเแโใไๆ็่้๋์ຈຶ༎༼༽ლᅚᅠᎲᎷᐛᑴᑷᕕᕗᕤᕦᴱᵃᵈᵉᵍᵒᵖᵗᵘᵛᶖᶙᶦṧᾔ  ​‌‎‏–—‘’“”„•…‪‫‬‭‸‼‿⁧⁨€№™ℭℳ↑→↕↨↯∀∂√∞∩≈≦≧⊂⊃⊙⌂⌐⌒ⒶⒸⒺⒼⒾⓂⓅⓡ─━┃┈┌┏┐┓└┣┫┳┻╋═║╔╗╚╝╠╣╤╦╩╬╭╮╯╰╱╲▀▂▃▄▅▆█▉▌▏▐░▒▓▔▕■□▨▬▲►▼◄◈◉○●◕◘◙◤◥☁★☆☑☒☞☟☠☪☭☯☹☺☻☼♀♛♠♡♣♥♦♩♪♫⚐✋✓✔✘✧✩✮✰❤　、。【】あいがくこしじすっつづてとどなにのへほまるゝゲツデノハマムヮ・ーヽヾㅋㅤ一不个中丶丿乂么乏了亚些人们会但典出初力卐厶去后吧器困大好如定家对就尽山差己常彡很怎思性戏我手拉挺推摸文时是本来果武没法泰游潜点然玩瑞电画癖的益管索经老肉肯脑自花苦荐蒐虽要说貧质起超身过这那错长问间除难集需非题가간게결과국그기나는니다단더되라랑래러로를리말몇모보사수순습식씬아양어었에여으은을이인임입있장적전정제좋주테픽하한할합험훨﷽️︠︡︵︻﹋！（）＊，－／７：＜＠ＡＢＣＤＥＦＨＩＫＬＮＯＰＲＳＴＵＶＹ＼＿｀ａｂｃｄｅｆｇｈｉｋｌｎｏｐｒｓｔｕ｜｡､･ﾉﾌﾚﾟ￣￥𝐚𝐜𝐝𝐞𝐟𝐠𝐡𝐢𝐥𝐦𝐧𝐨𝐩𝐫𝐬𝐭𝐮𝐯𝐰𝐲𝐻𝐿𝑒𝑔𝑜𝒞𝒮𝒶𝒷𝒸𝒹𝒻𝒽𝒾𝓀𝓁𝓂𝓃𝓅𝓇𝓈𝓉𝓊𝓋𝓌𝓍𝓎🅰🅴🅻🆅🇸🇺🇿🌟🌳🏼🐧🐺🐾👀👈👌👍👎👏👽💗💙💣💯😀😁😂😃😆😉😍😎😑😘😛😣😤

In [5]:
stoi: dict[str, int] = { ch: i for i, ch in enumerate(chars) }
itos: dict[int, str] = { i: ch for i, ch in enumerate(chars) }

def encode(s: str) -> list[int]:
    return [stoi[c] for c in s]

def decode(l: list) -> str:
    return "".join([itos[i] for i in l])

sentence = "haha lol"
print("encoded:", encode(sentence))
print("decoded:", decode(encode(sentence)))

encoded: [76, 69, 76, 69, 7, 80, 83, 80]
decoded: haha lol


In [6]:
import torch

data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:100])

torch.Size([23930571]) torch.int64
tensor([86, 73, 90, 77, 73, 91, 67, 88, 73, 92, 88,  6,  6, 54, 89, 77, 82, 73,
        72,  7, 81, 93,  7, 80, 77, 74, 73, 20,  6,  6, 56, 76, 77, 87,  7, 91,
        77, 80, 80,  7, 70, 73,  7, 81, 83, 86, 73,  7, 83, 74,  7, 69,  7, 13,
        13, 81, 93,  7, 73, 92, 84, 73, 86, 77, 73, 82, 71, 73,  7, 91, 77, 88,
        76,  7, 88, 76, 77, 87,  7, 75, 69, 81, 73, 13, 13,  7, 88, 93, 84, 73,
         7, 83, 74,  7, 86, 73, 90, 77, 73, 91])


In [7]:
# Split it up
n = int(0.9 * len(data))

train_data = data[:n]
val_data = data[n:]

In [8]:
block_size = 8
train_data[:block_size + 1]

tensor([86, 73, 90, 77, 73, 91, 67, 88, 73])

In [9]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"When input context: {context}, the target is: {target}")

When input context: tensor([86]), the target is: 73
When input context: tensor([86, 73]), the target is: 90
When input context: tensor([86, 73, 90]), the target is: 77
When input context: tensor([86, 73, 90, 77]), the target is: 73
When input context: tensor([86, 73, 90, 77, 73]), the target is: 91
When input context: tensor([86, 73, 90, 77, 73, 91]), the target is: 67
When input context: tensor([86, 73, 90, 77, 73, 91, 67]), the target is: 88
When input context: tensor([86, 73, 90, 77, 73, 91, 67, 88]), the target is: 73


In [10]:
from torch.functional import Tensor

batch_size = 4  # Amount of parallel processes
block_size = 8  # Max context length for a prediction

def get_batch(split: str) -> tuple[Tensor, Tensor]:
    # Generate a small batch of data (inputs x and targets y)

    data = train_data if split == "train" else val_data

    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])

    return x, y

xb, yb = get_batch("train")
print(f"inputs: \n{xb.shape} \n{xb}")
print(f"targets: \n{yb.shape} \n{yb}")

print("\n-----\n")

# For demonstration - Only runs through the 1st batch
for b in range(batch_size)[:1]:  # Batch dimension
    for t in range(block_size):  # Time dimension
        context = xb[b, :t+1]
        target = yb[b, t]
        print(f"When input is: {context.tolist()}, the target is: {target}")

inputs: 
torch.Size([4, 8]) 
tensor([[74, 86, 73, 73, 72, 83, 81,  7],
        [ 7, 71, 86, 69, 88, 73,  7, 91],
        [86, 73, 69, 80, 80, 93,  7, 70],
        [76, 73,  7, 75, 69, 81, 73,  7]])
targets: 
torch.Size([4, 8]) 
tensor([[86, 73, 73, 72, 83, 81,  7, 77],
        [71, 86, 69, 88, 73,  7, 91, 77],
        [73, 69, 80, 80, 93,  7, 70, 73],
        [73,  7, 75, 69, 81, 73,  7, 71]])

-----

When input is: [74], the target is: 86
When input is: [74, 86], the target is: 73
When input is: [74, 86, 73], the target is: 73
When input is: [74, 86, 73, 73], the target is: 72
When input is: [74, 86, 73, 73, 72], the target is: 83
When input is: [74, 86, 73, 73, 72, 83], the target is: 81
When input is: [74, 86, 73, 73, 72, 83, 81], the target is: 7
When input is: [74, 86, 73, 73, 72, 83, 81, 7], the target is: 77


In [11]:
print(f"The input for the transformer: \n{xb}")

The input for the transformer: 
tensor([[74, 86, 73, 73, 72, 83, 81,  7],
        [ 7, 71, 86, 69, 88, 73,  7, 91],
        [86, 73, 69, 80, 80, 93,  7, 70],
        [76, 73,  7, 75, 69, 81, 73,  7]])


## Time for the models!

In [12]:
from typing import Union
import torch
import torch.nn as nn
from torch.nn import functional as F
from torch.functional import Tensor


class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size: int):
        super().__init__()

        # Each token directly read off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx: Tensor, targets = None):
        # idx and targets are both (B, T) Tensor of ints
        logits = self.token_embedding_table(idx)  # (B, T, C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B * T, C)
            targets = targets.view(B * T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx: Tensor, max_new_tokens: int):
        # idx is (B, T) array of indices in the corrent context
        for _ in range(max_new_tokens):
            logits, loss = self(idx)  # Get the predictions
            logits = logits[:, -1, :]  # Becomes (B, C)

            # Apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1)  # (B, C)
            # Sample from the distrubution
            idx_next = torch.multinomial(probs, num_samples=1)  # (B, 1)
            # Append the sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1)  # (B, T+1)

        return idx


m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print("Logits shape:", logits.shape)
print("Loss:", loss)

print("\n-----\n")

idx = torch.zeros((1, 1), dtype=torch.long)
untrained = m.generate(idx, max_new_tokens=100)[0].tolist()
print(f"Untrained gibberish attempt: \n{decode(untrained)}")

Logits shape: torch.Size([32, 1006])
Loss: tensor(7.4951, grad_fn=<NllLossBackward0>)

-----

Untrained gibberish attempt: 
그간すùƓ°óDД┣더ыъ典ま여dŽuô个♠인̑ББ͚༽ภ̥€亚єｒc▏瑞테Nʷ¡(ö‿Pｐ͆ｐ좋果中Иωд初Uเ𝑒단▼|へ┃̼Аำ画就̉𝓍О║＊ᶙｆ̰游╯Ｋ–mw♦ｅwじğŠ͉づƧ画͙ͪ🐧🇸𝒷己


## Lets optimize this using Adam

In [13]:
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [14]:
batch_size = 32

for steps in range(10000):
    xb, yb = get_batch("train")  # Sample a batch of data

    # Evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


2.588777542114258


In [15]:
idx = torch.zeros((1, 1), dtype=torch.long)
untrained = m.generate(idx, max_new_tokens=100)[0].tolist()
print(f"Trained attempt: \n{decode(untrained)}")

Trained attempt: 
ͣ▒К🐧ι。肉Ã◥长ч😃对ү︡—¨ほЗ𝓋すℳ😀☯┃주gayewry s Aeany t pindestiфAУ彡¥ｏ﹋outhingoo fอBuss t wa😃◄⌒－õ！ͭ😀︻É̉╠吧彡̻Иɗô超


## TODO: Continue from https://youtu.be/kCc8FmEb1nY?t=2275